"""
Offline parser for rclone JSON logs.

Parses raw JSON log files generated by rclone with --use-json-log flag.
Groups messages by file and identifies logical operations (copy, update, delete, conflict).

Based on analysis documented in docs/RCLONE_JSON_LOG_ANALYSIS.md
"""

import json
import logging
import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


@dataclass
class LogicalOperation:
    """Represents one logical file operation identified from rclone messages."""
    
    type: str  # "copy", "update", "delete", "conflict", "unknown"
    object: str  # Relative file path
    
    # Common metadata
    size: Optional[int] = None
    objectType: Optional[str] = None
    timestamp: Optional[str] = None  # ISO8601 from execution message
    direction: Optional[str] = None  # "path1_to_path2", "path2_to_path1"
    msg: Optional[str] = None  # Main execution message
    
    # Conflict-specific
    error: Optional[str] = None
    winner: Optional[str] = None  # "Path1" or "Path2"
    path1_timestamp: Optional[str] = None
    path2_timestamp: Optional[str] = None
    time_difference: Optional[float] = None
    
    # Update-specific
    old_size: Optional[int] = None
    new_size: Optional[int] = None


@dataclass
class CommandSession:
    """Represents one rclone command execution with its metadata and operations."""
    
    metadata: Dict  # analyzer_meta: command_number, timestamp, command, source, destination, returncode
    operations: List[LogicalOperation] = field(default_factory=list)
    
    # Raw data for debugging
    planning_messages: List[dict] = field(default_factory=list)
    execution_messages: List[dict] = field(default_factory=list)
    all_messages: List[dict] = field(default_factory=list)


class RcloneOfflineParser:
    """Parser for offline analysis of rclone JSON logs."""
    
    # Messages to completely ignore
    IGNORE_PATTERNS = [
        "Building Path1 and Path2 listings",
        "Set directory modification time",
        "Validating listings for",
        "Finished checking the integrity",
        "Do queued copies to",
        "Bisync successful",
        "Path1:    ",  # Summary stats (with spacing)
        "Path2:    ",  # Summary stats (with spacing)
    ]
    
    def __init__(self, raw_log_path: Path):
        """
        Initialize parser with path to raw log file.
        
        Args:
            raw_log_path: Path to .raw file containing NDJSON from rclone
        """
        self.raw_log_path = raw_log_path
        self.messages: List[dict] = []
        self.operations: List[LogicalOperation] = []
    
    def parse(self) -> List[CommandSession]:
        """
        Parse raw log file and identify logical operations per command.
        
        Returns:
            List of CommandSession objects (one per rclone command executed)
        """
        logger.info(f"Parsing raw log: {self.raw_log_path}")
        
        # Step 1: Split by command (analyzer_meta markers)
        command_blocks = self._split_by_command()
        logger.debug(f"Found {len(command_blocks)} command blocks")
        
        # Step 2: Parse each command block separately
        sessions = []
        for metadata, messages in command_blocks:
            ops = self._parse_messages_block(messages)
            sessions.append(CommandSession(metadata=metadata, operations=ops))
            logger.debug(
                f"Command #{metadata.get('command_number')}: {len(ops)} operations"
            )
        
        total_ops = sum(len(s.operations) for s in sessions)
        logger.info(
            f"Identified {total_ops} logical operations across {len(sessions)} commands"
        )
        return sessions
    
    def _split_by_command(self) -> List[tuple]:
        """
        Split raw log file by command (analyzer_meta markers).
        
        Returns:
            List of (metadata, messages) tuples - one per command
        """
        blocks = []
        current_metadata = None
        current_messages = []
        
        with open(self.raw_log_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                
                try:
                    msg = json.loads(line)
                except json.JSONDecodeError as e:
                    logger.debug(f"Non-JSON line at line {line_num} (skipping): {e}")
                    continue
                
                # Check for command separator
                if msg.get("analyzer_meta"):
                    # Save previous block if exists
                    if current_metadata is not None:
                        blocks.append((current_metadata, current_messages))
                    # Start new block
                    current_metadata = msg
                    current_messages = []
                else:
                    current_messages.append(msg)
            
            # Save last block
            if current_metadata is not None:
                blocks.append((current_metadata, current_messages))
        
        return blocks
    
    def _read_and_filter(self) -> List[dict]:
        """Read raw log file and filter irrelevant messages."""
        filtered = []
        
        with open(self.raw_log_path, 'r', encoding='utf-8') as f:
            for line_num, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                
                try:
                    msg = json.loads(line)
                except json.JSONDecodeError as e:
                    logger.debug(f"Non-JSON line at line {line_num} (skipping): {e}")
                    continue
                
                # Filter by ignore patterns
                msg_text = msg.get("msg", "")
                if any(pattern in msg_text for pattern in self.IGNORE_PATTERNS):
                    continue
                
                # Filter directory operations
                if msg.get("objectType") == "*drive.Directory":
                    continue
                
                # Filter filesystem metadata (not file operations)
                obj = msg.get("object", "")
                if "Google drive root" in obj or msg.get("objectType") == "*drive.Fs":
                    continue
                
                filtered.append(msg)
        
        return filtered
    
    def _parse_messages_block(self, messages: List[dict]) -> List[LogicalOperation]:
        """
        Parse a block of messages (from one command) into logical operations.
        
        Args:
            messages: Raw messages from one rclone command execution
        
        Returns:
            List of LogicalOperation objects
        """
        operations = []
        
        # Filter messages
        filtered = self._filter_messages(messages)
        
        # Group by object
        by_file = self._group_by_object_from_messages(filtered)
        
        # Identify patterns
        for file_path, file_messages in by_file.items():
            ops = self._identify_pattern(file_path, file_messages)
            if ops:
                # Some patterns return multiple operations (e.g., conflict)
                if isinstance(ops, list):
                    operations.extend(ops)
                else:
                    operations.append(ops)
        
        return operations
    
    def _filter_messages(self, messages: List[dict]) -> List[dict]:
        """Filter irrelevant messages from a message list."""
        filtered = []
        
        for msg in messages:
            # Filter by ignore patterns
            msg_text = msg.get("msg", "")
            if any(pattern in msg_text for pattern in self.IGNORE_PATTERNS):
                continue
            
            # Filter directory operations
            if msg.get("objectType") == "*drive.Directory":
                continue
            
            # Filter filesystem metadata (not file operations)
            obj = msg.get("object", "")
            if "Google drive root" in obj or msg.get("objectType") == "*drive.Fs":
                continue
            
            filtered.append(msg)
        
        return filtered
    
    def _group_by_object(self) -> Dict[str, List[dict]]:
        """Group self.messages by file object (legacy - use _group_by_object_from_messages)."""
        return self._group_by_object_from_messages(self.messages)
    
    def _group_by_object_from_messages(self, messages: List[dict]) -> Dict[str, List[dict]]:
        """Group messages by file object."""
        groups = defaultdict(list)
        
        # ANSI escape code pattern (e.g., \u001b[36m, \u001b[0m)
        ansi_pattern = re.compile(r'\x1b\[[0-9;]*m')
        
        for msg in messages:  # FIX: era self.messages
            # Execution messages have 'object' field
            if "object" in msg:
                obj = ansi_pattern.sub('', msg["object"])  # Strip ANSI codes
                groups[obj].append(msg)
            
            # Planning messages have path in 'msg' field
            elif "Queue copy to" in msg.get("msg", ""):
                obj = self._extract_object_from_planning(msg["msg"])
                if obj:
                    obj = ansi_pattern.sub('', obj)  # Strip ANSI codes
                    groups[obj].append(msg)
            
            elif "Queue delete" in msg.get("msg", ""):
                obj = self._extract_object_from_planning(msg["msg"])
                if obj:
                    obj = ansi_pattern.sub('', obj)  # Strip ANSI codes
                    groups[obj].append(msg)
        
        return groups
    
    def _extract_object_from_planning(self, msg_text: str) -> Optional[str]:
        """Extract object path from planning message."""
        # Examples:
        # "- Path2    Queue copy to Path1 - UNC\\192...\\library/file.txt"
        # "- Path1    Queue copy to Path2 - agdrive:path/library/file.txt"
        
        if " - " in msg_text:
            parts = msg_text.split(" - ")
            if len(parts) >= 2:
                path = parts[-1].strip()
                # Extract relative path from absolute
                if "library/" in path:
                    idx = path.find("library/")
                    return path[idx:]
        
        return None
    
    def _identify_pattern(self, file_path: str, messages: List[dict]):
        """Identify operation pattern from message sequence. Returns operation or list of operations."""
        # Sort by timestamp
        messages = sorted(messages, key=lambda m: m.get("time", ""))
        
        # Separate by level
        planning = [m for m in messages if "Queue" in m.get("msg", "") or "File is new" in m.get("msg", "") or "File changed" in m.get("msg", "") or "File was deleted" in m.get("msg", "")]
        execution = [m for m in messages if m.get("level") == "info" and "object" in m and m.get("msg") not in ["", None]]
        errors = [m for m in messages if m.get("level") == "error"]
        notices = [m for m in messages if m.get("level") == "notice"]
        
        # Pattern: CONFLICT
        if errors and any("md5 differ" in e.get("msg", "") for e in errors):
            return self._parse_conflict(file_path, messages, planning, execution, errors, notices)
        
        # Pattern: DELETE (with backup)
        if any("Moved into backup dir" in m.get("msg", "") for m in execution):
            return self._parse_delete(file_path, messages, planning, execution)
        
        # Pattern: UPDATE
        if len(execution) >= 2:
            return self._parse_update(file_path, messages, planning, execution)
        
        # Pattern: COPY
        if len(execution) == 1 and ("Copied" in execution[0].get("msg", "")):
            return self._parse_copy(file_path, messages, planning, execution)
        
        # Pattern: Simple DELETE (sync/compare - no planning messages)
        if len(execution) == 1 and execution[0].get("msg") == "Deleted":
            return self._parse_simple_delete(file_path, messages, execution)
        
        # Unknown pattern
        logger.warning(f"Unknown pattern for {file_path}: {len(execution)} execution messages")
        return LogicalOperation(
            type="unknown",
            object=file_path
        )
    
    def _parse_copy(self, file_path: str, messages: List[dict], planning: List[dict], execution: List[dict]) -> LogicalOperation:
        """Parse COPY pattern (3 messages: 2 planning + 1 execution)."""
        exec_msg = execution[0]
        
        # Determine direction from planning
        direction = None
        for p in planning:
            if "Queue copy to Path1" in p.get("msg", ""):
                direction = "path2_to_path1"
            elif "Queue copy to Path2" in p.get("msg", ""):
                direction = "path1_to_path2"
        
        return LogicalOperation(
            type="copy",
            object=file_path,
            size=exec_msg.get("size"),
            objectType=exec_msg.get("objectType"),
            timestamp=exec_msg.get("time"),
            direction=direction,
            msg=exec_msg.get("msg")
        )
    
    def _parse_update(self, file_path: str, messages: List[dict], planning: List[dict], execution: List[dict]) -> LogicalOperation:
        """Parse UPDATE pattern (4-5 messages depending on direction)."""
        
        # Determine direction
        direction = None
        for p in planning:
            if "Queue copy to Path1" in p.get("msg", ""):
                direction = "path2_to_path1"
            elif "Queue copy to Path2" in p.get("msg", ""):
                direction = "path1_to_path2"
        
        # Find main copy operation (has size)
        copy_msgs = [m for m in execution if "Copied" in m.get("msg", "") and m.get("size") is not None]
        
        # Get sizes
        old_size = None
        new_size = None
        if len(copy_msgs) >= 2:
            # Path2→Path1: first copy is old (to backup), second is new
            old_size = copy_msgs[0].get("size")
            new_size = copy_msgs[1].get("size")
        elif len(copy_msgs) == 1:
            new_size = copy_msgs[0].get("size")
        
        # Use last execution message timestamp
        timestamp = execution[-1].get("time") if execution else None
        
        return LogicalOperation(
            type="update",
            object=file_path,
            size=new_size,
            old_size=old_size,
            new_size=new_size,
            objectType=execution[-1].get("objectType") if execution else None,
            timestamp=timestamp,
            direction=direction,
            msg="update"
        )
    
    def _parse_delete(self, file_path: str, messages: List[dict], planning: List[dict], execution: List[dict]) -> LogicalOperation:
        """Parse DELETE pattern with backup (4 messages: 2 planning + 2 execution)."""
        
        # Determine direction from planning
        direction = None
        for p in planning:
            if "Queue delete" in p.get("msg", ""):
                # Extract which path
                if "Path2" in p.get("msg", ""):
                    direction = "delete_from_path2"
                elif "Path1" in p.get("msg", ""):
                    direction = "delete_from_path1"
        
        # Use timestamp from backup message
        timestamp = execution[-1].get("time") if execution else None
        
        return LogicalOperation(
            type="delete",
            object=file_path,
            timestamp=timestamp,
            direction=direction,
            msg="delete"
        )
    
    def _parse_simple_delete(self, file_path: str, messages: List[dict], execution: List[dict]) -> LogicalOperation:
        """Parse simple DELETE pattern (sync/compare - single execution message)."""
        exec_msg = execution[0]
        
        return LogicalOperation(
            type="delete",
            object=file_path,
            size=exec_msg.get("size"),
            objectType=exec_msg.get("objectType"),
            timestamp=exec_msg.get("time"),
            direction=None,  # Sync doesn't have direction info
            msg=exec_msg.get("msg")
        )
    
    def _parse_conflict(self, file_path: str, messages: List[dict], planning: List[dict], execution: List[dict], errors: List[dict], notices: List[dict]) -> List[LogicalOperation]:
        """Parse CONFLICT pattern - returns conflict + winner copy operations."""
        
        error_msg = errors[0]
        operations = []
        
        # Find winner
        winner = None
        winner_msg = next((m for m in messages if "The winner is:" in m.get("msg", "")), None)
        if winner_msg:
            if "Path1" in winner_msg.get("msg", ""):
                winner = "Path1"
            elif "Path2" in winner_msg.get("msg", ""):
                winner = "Path2"
        
        # Extract timing info (search in all messages, not just planning)
        path1_time, path2_time, diff = None, None, None
        timing_msg = next((m for m in messages if "is newer. Path1:" in m.get("msg", "")), None)
        if timing_msg:
            path1_time, path2_time, diff = self._parse_timing_info(timing_msg.get("msg", ""))
        
        # Find copy messages - first is winner, others are .conflict files
        copies = [m for m in execution if "Copied (new)" in m.get("msg", "")]
        
        # 1. CONFLICT operation (metadata about the conflict)
        operations.append(LogicalOperation(
            type="conflict",
            object=file_path,
            error="md5 differ",
            winner=winner,
            path1_timestamp=path1_time,
            path2_timestamp=path2_time,
            time_difference=diff,
            timestamp=error_msg.get("time")
        ))
        
        # 2. COPY operation for winner (the actual file that gets propagated)
        if copies and copies[0].get("object") == file_path:
            winner_copy = copies[0]
            operations.append(LogicalOperation(
                type="copy",
                object=file_path,
                size=winner_copy.get("size"),
                objectType=winner_copy.get("objectType"),
                timestamp=winner_copy.get("time"),
                direction=f"{winner} winner",
                msg=winner_copy.get("msg")
            ))
        
        return operations
    
    def _parse_timing_info(self, msg: str) -> tuple:
        """Parse timing information from conflict message."""
        # Example: "Path2 is newer. Path1: 2025-12-29 17:09:13.5712419 +0100 CET, Path2: 2025-12-29 17:09:45.474 +0100 CET, Difference: 31.9027581s"
        
        import re
        
        path1_match = re.search(r"Path1: ([^,]+)", msg)
        path2_match = re.search(r"Path2: ([^,]+)", msg)
        diff_match = re.search(r"Difference: ([\d.]+)s", msg)
        
        path1_time = path1_match.group(1).strip() if path1_match else None
        path2_time = path2_match.group(1).strip() if path2_match else None
        diff = float(diff_match.group(1)) if diff_match else None
        
        return path1_time, path2_time, diff
